spring.application.name=onlinebanking
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/online_banking
spring.datasource.username=bank_user
spring.datasource.password=bank@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=MyOnlineBankingJwtSecretKeyForDevelopmentOnly123456789
jwt.expiration=86400000

logging.level.org.springframework.security=TRACE